let Monal = {
        resturentName: "Monal",
        ownerDetails: {},
        ownerName: "Luqman Ali Afzal",
        location: "‎Pir Sohawa Road, Islamabad",
        openingDate‎: ‎"05-11-1969",
        openingHour: ‎"9AM--12AM",
        phoneNo: "(051) 2898044",
        profile: "instagram",
        atYoutube: "http://www.youotube.com/watch?v=MdAqnZwYFyQ",
        atFacebook: "http://www.facebook.com/TheMonalResturantIslamabad",
        rating: " Rating: 4.4 - ‎38,661 vote",
        way: "at Highest peak of mountain",
        address:  "9KM Pir Sohawa Rd, Islamabad, Islamabad Capital Territory",
        height: "Height of Pir Sohawa is 1524 meters (5000 feet) above seal level",
        quantityOfWaiters: 100,
        noOfFullStaff: 200,
        noOfTables: 500,
        noOFChairs: 5000,
        areas: ["play area", "hi-tea area", "reception", "birthday party areas", 
               "family areas"],
        deals: ["family deals", "kids deals", "ramzan iftar/sehri deals",
               "fast food deals", "italian deals", "pakistani deals", "sweetitems deals",
                "spicy food deals"],
        staff: [
            {
                name: "M.Afzal" ,
                postion: "Manager",
                salary: "handsome Salary",
                workTiming: "12 hours",
                qualification: "masters in accounts",
                gender: "male",
                experience: "10 years",
                contactNo: "0323-547890",
                email: "afzal@gamil.com",
                anotherAcount: "facebook or instagram",
            },
            {
                name: "safdar",
                postion: "ceo",
                salary: 50000,
                workTiming: "12 hours",
                qualification: "phd",
                gender: "male",
                experience: "20 years",
                contactNo: "0324-68798098",
                email: "safdar@gamail.com",
                anotherAcount: "no",
            },
            {
                name: "Saad" ,
                postion: "head of mangment",
                salary: 100000,
                workTiming: "12 Hours",
                qualification: "masters in finance",
                gender: "male",
                experience: "15 years",
                contactNo: "0342-7687875",
                email: "saad@gmail.com",
                anotherAcount: "no",
            },
            {
                name: "sofia",
                postion: "head of staff",
                salary: 40000,
                workTiming: "12 hours",
                qualification: "graduate",
                gender: "female",
                experience: "5 years",
                contactNo: "0309-25618721",
                email: "sofianaz@gamial.com",
                anotherAcount: "instagram",
            }
        ],
        openHours: {
            Saturday: "9am–12:30am",
            Sunday: "9am–12:30am",
            Monday: "9am–12:30am",
            Tuesday:	"9am–12:30am",
            Wednesday: "9am–12:30am",
            Thursday: "9am–12:30am",
            Friday: "9am–12:30am",
        },
        Phone: "(051) 2898044",
        quantityOfVariety: "300",
    pakistaniBreakFast: ["Choice of Fresh Seasonal Juice(300 ml)",
                        "Lassi Two Farm Fresh Eggs", "Lahori Chanay Poori(2 Pieces)", 
                        "Pakistani Paratha(1 piece)", "Suji Halwa Poodinay Walay Aloo", 
                        "Tea / Coffee / Green Tea"],
    continentalBreakFast: ["Choice of Fresh Seasonal Juice(300 ml)",
                        "Lassi Two Farm Fresh Eggs", "Lahori Chanay Poori(2 Pieces)", 
                        "Pakistani Paratha(1 piece)", "Suji Halwa Poodinay Walay Aloo", 
                        "Tea / Coffee / Green Tea"],
    hiTeaTimings: ["Monday to Saturday",
                    "1st Slot: 01:00 PM to 02:30 PM",
                    "2nd Slot: 03:00 PM to 04:30 PM",
                    "3rd Slot: 05:00 PM to 06:30 PM",
                    "Sunday",
                    "1st Slot: 03:00 PM to 04:30 PM",
                    "2nd Slot: 05:00 PM to 06:30 PM"],
    dinnerBuffetTiming: ["Every day from 7:15 PM – 11:30 PM in Two Slots",
                        "1st slot 7:15 pm to 9:15 pm",
                        "2nd slot 9:30 pm to 11:30 pm"],
    forReservationNo: "042 35789823, 24, 25",
    monalSundayBrunchprice: "Rs. 1085+Taxes",
    monalSundayBrunchMenu: ["Chicken Seekh Kabab", "Chicken Boti", "Chicken Karahi", "Zeera Pulao", 
                            "Piya-Kulcha", "Beef Nehari", "Chicken Haleem", "Chicken tawa qeema",
                            "lahori chirga", "Aloo Bhujia", "Beef Qeema", "Chicken tikka",
                           "Seekh Kabab", "Chana Chaat", "Aloo Keema", "Samosas", "Sajji", "Haleem"],
    platterPrice: {
        chinesePlatter: "Rs.765",
        continentalPlatter: "Rs.765",
        italianPlatter: "Rs.865",
        kabuliPlatter: "RS.765",
        kidsPlatter: "Rs.595",
        muttonLoversPlatter: "Rs.1045",
        thaiPlatter: "Rs.765",
        vegetraianPlatter: "Rs.765",
        pakistaniPlatter: "Rs.765",
    },   
    iftarDishes: ["Iranian Khajoor", "Dahi Baray", "Fruit Chaat", "Chinese Meat Balls",
                "Cheese Naan", "BBQ Chicken Wings", "Aalo Samosa", "Assorted PAkoras",
                "Monal Special Potato Cutlus", "Chicken/Cheese Sandwiches", "Frosted Lemonade",
                "Mint Lemonade", "Nestle Lemon / Orange", "Mix Tea / Green Tea"],
    mainCoursesOfIftar: ["chicken reshmi tikka(boneless)", "chicken achari boti (with bone)",
                        "chicken gola kabab", "batter fried fish & chips", "mutton karahi (with bone)",
                        "chicken makhni(boneless)", "kabuli pilao", "thai chicken with cashew nuts",
                        "chicken manchorian"],
    branchesCity: ["rawalpindi", "islamabad", "faisalabad", "lahore"],
    searchRelatedToMonalDetails: [
        "monal islamabad menu",
        "monal islamabad heights",
        "monal islamabad buffet rates 2019",
        "monal resturant islamabad menu rates 2018", 
        "monal islamabad buffet per head",
        "monal islamabad islamabad pics",
        "monal islamabad hi tea",
        "monal resturant islamabad platter price",
    ],
    menu: ["Bread & Naans", "Meaty Bites", "Wings", "Frnch Fries", "Soups"],
    items: ["FastFood", "Continental", "From around the World", "Rice Variety", "Oriental",
        "Golden Grill", "Special Deals Family Deals", "Individual Deals", "Hi-Tea", "Meal Deals",
        "Namkeen", "Salad Bar", "Freshly Baked", "Meetha", "Thin Crust Pizza", "Deep Pan Pizza",
        "Italian Pasta & Lasagna", "Fresh Juices", "MilkShakes", "Summer Coolers", "Chilling Corner",
        "Ice Cream Shakes", "Ice Cream Treats", "Beat the Heat", "Seasonal Dessert", "Winter Warmers",
        "Cakes,Bakes and Dessert", "Special Drinks", "Live Kitchen"],
    sections: ["Tawa Section", "Namkeen SEction", "Fish Section", "Desserts"],
    dessertMenu: [
        {
            name: "Sizzling Brownie & ICe cream",
            price: "Rs.345",
        },
        {
            name: "Molten Chocolate Cake",
            price: "Rs.525",
        },
        {
            name: "Bread and Butter Pudding",
            price: "Rs.525",
        },
        {
            name: "Cheese Cake Slice",
            price: "Rs.335",
        },
        {
            name: "Chocolate Fudge Cake Slice",
            price: "Rs.335",
        },
        {
            name: "Mousse Cake Slice",
            price: "Rs.395",
        },
        {
            name: "Cramel Coffee Cake Slice",
            price: "Rs.335",
        },
        {
            name: "Ice Cream Cake Slice",
            price: "Rs.395",
        },
    ],
    specialDrinks: [
        {
            name: "Pina Colada",
            price: "Rs.425",
        },
        {
            name: "Blue Lagon",
            price: "Rs.425",
        },
        {
            name: "Kit Kat Kold Kofee",
            price: "Rs.525",
        },
        {
            name: "Cold Coffee",
            price: "Rs.425",
        },
        {
            name: "Frosted Lemonade",
            price: "Rs.215",
        },
        {
            name: "Mint Lemonade",
            price: "Rs.255",
        },
        {
            name: "Freenze",
            price: "Rs.425",
        },
        {
            name: "Mandarin Ambrosia",
            price: "Rs.425",
        },
        {
            name: "Summer Blend",
            price: "Rs.425",
        },
        {
            name: "Captain Blue",
            price: "Rs.425",
        },
    ]
    fastFood: [
        {
            name: "Chicken Steak Burger in Pepper Sauce",
            price: "Rs.855",  
        },
        {
            name: "Chicken Steak Burger in Mushroom Sauce",
            price: "Rs.855",  
        },
        {
            name: "Beef Steak Burger in Pepper Sauce",
            price: "Rs.855",  
        },
        {
            name: "Beef Steak Burger in Mashroom Sauce",
            price: "Rs.795",  
        },
        {
            name: "Chicken Burger",
            price: "Rs.595",  
        },
        {
            name: "Chicken Double Decker Burger",
            price: "Rs.695",  
        },
        {
            name: "Chiken Cheese Burger",
            price: "Rs.655",  
        },
        {
            name: "Fried Chicken Breast Burger",
            price: "Rs.695",  
        },
        {
            name: "Fried Chicken Breast Burger With Cheese",
            price: "Rs.745",  
        },
        {
            name: "Grill Chicken Burger",
            price: "Rs.635",  
        },
        {
            name: "Monal Special Burger",
            price: "Rs.745",  
        },
        {
            name: "Beef Cheese Burger",
            price: "Rs.635",  
        },
        {
            name: "Chicken Sandwich",
            price: "Rs.585",  
        },
        {
            name: "Club Sandwich",
            price: "Rs.695",  
        },
        {
            name: "Roast Chicken Sandwich",
            price: "Rs.665",  
        },
        {
            name: "Chicken Shawarma",
            price: "Rs.445",  
        },
        {
            name: "",
            price: "Rs.425",  
        },
        {
            name: "",
            price: "Rs.425",  
        },
        {
            name: "",
            price: "Rs.425",  
        },
    ]

    }
